// clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import './App.css';
import './index.css';
import { useNavigate } from 'react-router-dom';
import { useHistory } from 'react-router-dom';
import ControleLivro from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

function LivroDados() {
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(0);
    const history = useHistory();

    function tratarCombo(evento) {
        setCodEditora(Number(evento.target.value));
    }

    const incluir = (evento) => {
        evento.preventDefault();
        // Implemente a lógica de inclusão do livro aqui
        history.push('/');
    };

    return (
        <main className="livro-dados-container">
            <h1>Incluir Livro</h1>
            <form className="livro-dados-form" onSubmit={incluir}>
                <input
                    type="text"
                    placeholder="Título"
                    value={titulo}
                    onChange={(e) => setTitulo(e.target.value)}
                />
                <textarea
                    placeholder="Resumo"
                    value={resumo}
                    onChange={(e) => setResumo(e.target.value)}
                />
                <input
                    type="text"
                    placeholder="Autores"
                    value={autores}
                    onChange={(e) => setAutores(e.target.value)}
                />
                <select value={codEditora} onChange={tratarCombo}>
                    {/* Adicione as opções das editoras aqui */}
                </select>
                <button type="submit">Incluir</button>
            </form>
        </main>
    );
}

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro();  
  public autoresForm: string = '';  
  public editoras: Array<Editora> = [];  // inicia com um array vazio

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();  
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');  
    this.servLivros.incluir(this.livro); 
    this.router.navigateByUrl('/lista');  
  }
}

<main class="container">
    <h1 class="mt-5">Incluir Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="mb-3">
            <label for="titulo" class="form-label">Título</label>
            <input type="text" class="form-control" id="titulo" required [(ngModel)]="livro.titulo">
        </div>

        <div class="mb-3">
            <label for="resumo" class="form-label">Resumo</label>
            <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo"></textarea>
        </div>

        <div class="mb-3">
            <label for="editora" class="form-label">Editora</label>
            <select class="form-select" id="editora" required [(ngModel)]="livro.codEditora">
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{editora.nome}}</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="autores" class="form-label">Autores</label>
            <textarea class="form-control" id="autores" [(ngModel)]="autoresForm"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Incluir Livro</button>
    </form>
</main>
